### ISSUE TITLE
PostgreSQL jdbc driver version mismatch.

### ISSUE THREAD

**Issue by whitingjr** [hpehl/example-bare-metal-app#1]
The driver [42.2.5](https://github.com/hpehl/example-bare-metal-app/blob/main/install.sh#L114) version defined in install.sh does not match with the backend project or helm [chart](https://github.com/luck3y/example-openshift-app/blob/main/eapxp4/app.yaml#L10).

**Comment by hpehl** [comment]
Fixed by #2
